### ISSUE TITLE
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

### ISSUE THREAD

**Issue by MerlijnBusch** [danieltabrizian/CodeGeneration#1]
Running the https://github.com/danieltabrizian/CodeGeneration/blob/testing/src/test/RegisterControllerTest.java class geeft deze error we hebben geen idee waarom

**Comment by wimmelstein** [comment]
Beste studenten.

1. De controller die je test doet teveel dingen. Het creëert een user en retourneert een DTO terug met de UserEntity en een token. Dat klopt niet. Een register functie slaat een username en password op in de database en geeft die user terug. Pas bij het inloggen krijg je een token. Deze functie doet dus teveel en dat is heel lastig testen
2. Jullie pom.xml is volledig vervuild. Jullie hebben verschillende mockito dependencies gedownload, terwijl spring-boot-starter-test al van alles heeft, o.a. junit5. Bovendien hebben jullie een te lage springboot versie.
3. Ik heb een patch file gemaakt, welke ik heb toegevoegd. Als je deze uitvoert, dan werkt het nog niet, want je krijgt een 403 ipv een 200, maar nu kun je in ieder geval kijken wat je nog verder moet doen. 

Mijn advies: trek de RegisterApiController en het creëren van een token uit elkaar.

[Fixed_environment_of_sorts.patch.zip](https://github.com/danieltabrizian/CodeGeneration/files/8818155/Fixed_environment_of_sorts.patch.zip)

**Comment by MerlijnBusch** [comment]
We hebben alles geupdate alleen is de error nu een 401 ook had ik de object mapper terug moeten zetten in de constructor waardoor de error in de test class Parameter 0 of constructor in io.swagger.api.RegisterApiController required a bean of type 'com.fasterxml.jackson.databind.ObjectMapper' that could not be found. is geworden want als ik niet dat in de constructor zet dan werkt de regristreer functie niet meer. Ook kunnen we de spring boot versie niet omhoog zetten vanwege swagger dependecie want dan runt het programma ook niet meer?

Kan u hier na kijken en kijken wat we kunnen verbeteren
