### ISSUE TITLE
Cucumbur loads spring but doesnt execute test on MASTER branch

### ISSUE THREAD

**Issue by MerlijnBusch** [danieltabrizian/CodeGeneration#2]
Cucumbur loads spring but doesnt execute test

**Comment by wimmelstein** [comment]
I have made your first test working. You take it from there
[Fixed_config_First_test_working.patch.zip](https://github.com/danieltabrizian/CodeGeneration/files/8867814/Fixed_config_First_test_working.patch.zip)
